name: screening35
channels:
  - https://repo.anaconda.com/pkgs/free
  - conda-forge
  - mosdef
  - omnia
  - choderalab
  - openbabel
  - defaults
dependencies:
  - altair=2.2.2
  - appdirs=1.4.3
  - appnope=0.1.0
  - argon2_cffi=18.1.0
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - automat=0.7.0
  - backcall=0.1.0
  - bcrypt=3.1.4
  - biopython=1.72
  - blas=1.1
  - bleach=3.1.0
  - blosc=1.17.0
  - boost=1.66.0
  - boost-cpp=1.66.0
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - cairo=1.14.12
  - certifi=2018.8.24
  - cffi=1.11.5
  - cftime=1.0.1
  - clang=8.0.1
  - clang-tools=8.0.1
  - clangdev=8.0.1
  - clangxx=8.0.1
  - cloog=0.18.0
  - constantly=15.1.0
  - cryptography=2.3
  - cryptography-vectors=2.3
  - curl=7.63.0
  - cycler=0.10.0
  - cython=0.28.5
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.2.3
  - fftw3f=3.3.4
  - flake8=3.5.0
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gcc=4.8.5
  - gettext=0.19.8.1
  - glib=2.58.3
  - gmp=5.1.2
  - griddataformats=0.5.0
  - gsd=1.5.3
  - hdf4=4.2.13
  - hdf5=1.10.2
  - html5lib=1.0.1
  - hyperlink=17.3.1
  - icu=58.2
  - idna=2.7
  - incremental=17.5.0
  - intel-openmp=2019.4
  - ipdb=0.12.2
  - ipykernel=5.1.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.3.1
  - isl=0.12.2
  - jedi=0.12.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9c
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyterlab=0.34.1
  - jupyterlab_launcher=0.13.1
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libclang=8.0.1
  - libcurl=7.63.0
  - libcxx=8.0.1
  - libcxxabi=8.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libllvm8=8.0.1
  - libnetcdf=4.6.1
  - libopenblas=0.2.20
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libxml2=2.9.9
  - llvm-meta=8.0.0
  - llvm-tools=8.0.1
  - llvmdev=8.0.1
  - lz4-c=1.8.3
  - markupsafe=1.0
  - mccabe=0.6.1
  - mdanalysis=0.18.0
  - mdtraj=1.9.1
  - mistune=0.8.3
  - mkl=2019.4
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - mmtf-python=1.1.2
  - more-itertools=7.2.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - msgpack-python=0.5.6
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf4=1.4.1
  - networkx=2.3
  - notebook=5.6.0
  - numexpr=2.6.6
  - numpy=1.15.2
  - numpy-base=1.14.3
  - olefile=0.46
  - openbabel=2.4.1
  - openblas=0.2.20
  - openmm=7.3.1
  - openssl=1.0.2r
  - pandas=0.23.4
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - passlib=1.7.1
  - pathlib=1.0.1
  - pathlib2=2.3.2
  - patsy=0.5.1
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.2.0
  - pip=18.0
  - pixman=0.34.0
  - pluggy=0.7.1
  - prometheus_client=0.7.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - py=1.8.0
  - pyasn1=0.4.6
  - pyasn1-modules=0.2.6
  - pycairo=1.17.1
  - pycodestyle=2.3.1
  - pycparser=2.19
  - pyflakes=1.6.0
  - pygments=2.4.2
  - pyhamcrest=1.9.0
  - pymongo=3.7.1
  - pyopenssl=18.0.0
  - pyparsing=2.4.2
  - pyqt=5.6.0
  - pytables=3.4.4
  - pytest=3.7.2
  - python=3.5.5
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtconsole=4.5.3
  - rdkit=2018.03.3
  - readline=7.0
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=18.1.0
  - setuptools=40.0.0
  - signac=1.2.0
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - swig=4.0.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.10.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - twisted=17.5.0
  - typing=3.6.6
  - uncertainties=3.0.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.3.1
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope.interface=4.5.0
  - zstd=1.4.0
  - pip:
    - cloudpickle==0.8.0
    - deprecation==2.0.6
    - matplotlib==3.0.3
    - mock==3.0.5
    - packaging==19.0
    - signac-flow==0.7.1

